### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by jqespinosa** [hoppula/refire-forum#1]
Good day, I was trying to run npm run build but gets error below. Thanks

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild refire-forum@1.1.0
7 info build refire-forum@1.1.0
8 verbose unsafe-perm in lifecycle true
9 info refire-forum@1.1.0 Failed to exec build script
10 verbose stack Error: refire-forum@1.1.0 build: `npm run clean && npm run build:webpack && npm run html`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid refire-forum@1.1.0
12 verbose cwd C:*************\refire\refire-forum
13 error Windows_NT 6.3.9600
14 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error refire-forum@1.1.0 build: `npm run clean && npm run build:webpack && npm run html`
18 error Exit status 1
19 error Failed at the refire-forum@1.1.0 build script 'npm run clean && npm run build:webpack && npm run html'.
19 error This is most likely a problem with the refire-forum package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run clean && npm run build:webpack && npm run html
19 error You can get their info via:
19 error     npm owner ls refire-forum
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by hoppula** [comment]
I suspect it's because the `html` npm task uses `cp` command which is not available in Windows. I guess we could use some lib like [shx](https://github.com/shelljs/shx) for all the shell commands in npm scripts so they'd also work in Windows. 

Meanwhile, as a workaround, you can edit the build task to look like:
`npm run clean && npm run build:webpack` 
and then just manually copy the `index.html` file from root to `dist` folder.

**Comment by jqespinosa** [comment]
Tried the workaround did not work and same error is produced.

.....
18 error refire-forum@1.1.0 build: `npm run clean && npm run build:webpack`
18 error Exit status 1
19 error Failed at the refire-forum@1.1.0 build script 'npm run clean && npm run build:webpack'.
19 error This is most likely a problem with the refire-forum package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run clean && npm run build:webpack
19 error You can get their info via:
19 error     npm owner ls refire-forum
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

I have tried the process on a Mac and successfully deployed on Firebase. However, the main page only shows a loading screen. Currently troubleshooting as this is a separate concern.

Will close this issue. Thank you.
