### ISSUE TITLE
SSR + Next.js?

### ISSUE THREAD

**Issue by ghost** [hoppula/refire-forum#15]
Hey!
I'm trying to figure out how to get bindings to play with Next.js and SSR. Any idea if it is possible to get refire-app synced with next-redux-wrapper and the redux store?

Thanks!

**Comment by hoppula** [comment]
Hi. I haven't played around with Next.js yet, but it's really interesting piece of tech.

I think you could somehow check that `props._status.initialFetchDone` is true in Next.js' component's `getInitialProps`, that way you could defer rendering until wanted content is ready for SSR.

I'm planning to add better SSR support to refire-app in the future, it's quite trivial to add basic hydrate&dehydrate, just haven't had the need for SSR in any Firebase project yet.
However, I think there are still some big limitations in Firebase Node.js client, SSR with authentication is going to be really difficult to implement.
