### ISSUE TITLE
How can it be hosted in Firebase Host? 

### ISSUE THREAD

**Issue by AdrianoW** [hoppula/refire-forum#16]
Hi

I have tried to run the forum in Firebase's hosting but was not able to. I am missing something?

Steps:
- Added apiKey and projectId on src/config.js
- Ran `npm run build` 
- ran `npm run deploy`

A white screen only showed up.

I have than tried running the `firebase init` where I set my public folder to be the dist folder. Followed the same previous steps. Now the loading icon shows up but that is all.

Any ideas? Maybe a how to deploy on the readme.md could be a good thing.

**Comment by hoppula** [comment]
Hi. 

Did you also run `npm run login` and `npm run bootstrap` as described in [https://github.com/hoppula/refire-forum#deploying-your-own-instance](https://github.com/hoppula/refire-forum#deploying-your-own-instance)? 

That white screen sounds like it's missing the initial data structure in Firebase. However, if you already ran those steps then I'll have to take a look and see if something has broken in the setup process.

**Comment by AdrianoW** [comment]
Yeap, done all that. Locally it is running flawlessly.

**Comment by FaizanDurrani** [comment]
having the same issue, please fix

**Comment by Kinark** [comment]
Facing the same problem, seems like only index.html is being copied (and deployed) to dist folder.

**Comment by hoppula** [comment]
There was a problem with outdated `react-tap-event-plugin` dependency (previously discussed in #14). Latest commit to master fixes this, I was able to deploy working instance to Firebase hosting with steps provided in README.
