### ISSUE TITLE
email and password login

### ISSUE THREAD

**Issue by danwguy** [hoppula/refire-forum#17]
On my project I am only using email and password login. This is for my app that I am building. I want to have a web forum, that won't be available in the mobile app, just from the web. That's where this comes in, however, I am not using google, facebook, or any other login system, I am using the standard email and password login with firebase. I would like my users to be able to login to the web app the exact same as if they logged in to the mobile app, but I can't find where to enable the email and password login with refire. The only options I see are the provider logins. Is there any possible way to allow users to login with email and password and not have to use one of the providers?

**Comment by hoppula** [comment]
Currently all the available providers are implemented using `FirebaseOAuth` component, as seen in https://github.com/hoppula/refire-forum/blob/master/src/App/AuthenticationMenu.js#L103-L113

You can implement email & password login by creating your own Login component using refire's [FirebaseLogin HOC](https://github.com/hoppula/refire/blob/master/docs/FirebaseLogin.md). 

That `LoginComponent` in the documentation example receives `email` and `password` strings which are the current values for your login form. You can update them using `updateEmail` and `updatePassword` functions and then submit the form using `submit` prop function.

I currently have no time to add email & password login as another login option but if you end up writing an implementation and are willing to open source it, I could look in to integrating it to refire-forum :+1:
