### ISSUE TITLE
stuck at firebase login/bootstrap

### ISSUE THREAD

**Issue by 29er** [hoppula/refire-forum#2]
Hey im Just going through the steps to deploy.
ive set up my FB app and set the name etc.

once I get to step 4:  'npm run login'
I get these errors:

```
>firebase login
sh: firebase: command not found
```

I tried 'npm install firebase --save' , but to no avail....
Probably something I am forgetting ?
Thanks!

**Comment by hoppula** [comment]
Oh, it seems that the dependencies are missing `firebase-tools` :) 

I have to add `firebase-tools` package to devDependencies and ensure that the scripts work without global install. 

For now, you can install `firebase-tools` globally by running:
`npm install -g firebase-tools`

Thanks for the info :+1:

**Comment by 29er** [comment]
ahh ok thanks!
