### ISSUE TITLE
Size of project with node modules is too high

### ISSUE THREAD

**Issue by hamzadiaz** [hoppula/refire-forum#20]
Is there a way to omit some node modules because the project size is about 200MB after loading all required node modules.

**Comment by hoppula** [comment]
That's unfortunate but that's just the way it is with Node.js and development dependencies :( 
Actual app bundle is luckily "just" 535 KB minified & gzipped. There's room for improvement for sure, but I don't currently have any time to work on this project, so if you or someone else has time to help, I'll gladly review PRs 👍
