### ISSUE TITLE
about adding admin users

### ISSUE THREAD

**Issue by YounesBelbaz** [hoppula/refire-forum#21]
how can I create

"adminUsers": {
  "google:123456789": true
}

Error: Syntax error in database rules:
4:36: Expected '{'.
can you explain that?

**Comment by hoppula** [comment]
Check out https://github.com/hoppula/refire-forum/blob/master/bootstrap.json , you can add the account under `adminUsers` there and if you run `npm run bootstrap` it will be added to your database. Be aware that running this will clear your database :)

**Comment by YounesBelbaz** [comment]
thank you very much for helpful 👍  :)
