### ISSUE TITLE
Admin user added but not showing when logged in

### ISSUE THREAD

**Issue by sleeplesseditor** [hoppula/refire-forum#22]
I've followed your instructions about adding a user's UID in the 'userAdmin' object in bootstrap.json, and it's appearing in the Firebase database I set up, but when I log in as that user into my instance of the database, I'm not seeing any of the admin features. Am I missing something obvious?

**Comment by sleeplesseditor** [comment]
Sorted it – wasn't entering the info into userAdmin correctly!

**Comment by hoppula** [comment]
Good that you got it sorted out, maybe I could improve the documentation a bit regarding the admin user addition.
