### ISSUE TITLE
Dont have admin features

### ISSUE THREAD

**Issue by bsde1234** [hoppula/refire-forum#29]
My bootstrap.json
```
"adminUsers": {
    "google:10912870198101xxx6012": true
  },
...
```
and I issued,
`npm run bootstrap`.
But I dont get admin features when logged in.

**Comment by JimKay1941** [comment]
Well you are one big step ahead of me! I cannot figure out what:
"Create 'adminUsers' path in your Firebase" means. 
Well I suppose I do know what it means, but the Firebase documentation is sufficiently sparse that I have no actual idea how to do that.

**Comment by bsde1234** [comment]
@JimKay1941 https://github.com/hoppula/refire-forum/issues/21#issuecomment-371088130

**Comment by JimKay1941** [comment]
Same for me. I just did what you did. I added my uid to the adminUsers thingy in bootstrap.json and ran npm run bootstrap which dutifully wipes out the entire (tiny) database but does nothing about making me an administrator. 

I do notice that the authors have stopped paying any attention to this system and are ignoring reports of problems. 

Maybe they realize this system isn't attracting any new users.

Yesterday and today, I created a phpBB system on my Windows 10 workstation and I'm running that in the background. I'm using DDNS and forwarding. I got it all working in two days. The second day (today) was eaten up by figuring out how to get port 80 to be forwarded through my three serially connected routers. The EDIMax router was the really difficult one. I sort of don't expect anyone is going to hack through those three routers any time soon. 

Each router has its own Wi-Fi so I connected my phone to them one at a time and tinkered until I could connect to the VM. At one point I'd lost all logon to the ISP's router/modem but I got back in by cabling my laptop in directly. Then I fixed my mistaken attempt. In the end, it did start working.

As frustrating as that was, it was so much easier than what I went through with Hoppula. It's still rather useless, if you ask me.

**Comment by bsde1234** [comment]
I think this script is still working. How do you get your google uid? may be we did some mistake.

**Comment by JimKay1941** [comment]
I logged on to the fire base console and poked around the database where I found my userid code. I used that as the value. There were only two userids in there, both mine. 

The database linked my two gmail addresses, each with a user code.

**Comment by bsde1234** [comment]
I think that is not userid, that is logged in time like last loggedin time. User id is something different I think

**Comment by JimKay1941** [comment]
![Capture](https://user-images.githubusercontent.com/892513/70404679-100b9600-19f8-11ea-96fa-476066abd4b2.JPG)

**Comment by JimKay1941** [comment]
Well look for yourself!

**Comment by JimKay1941** [comment]
That is, by the way, the 'realtime database' you are looking at.

**Comment by bsde1234** [comment]
I get admin rights with that settings

**Comment by bsde1234** [comment]
I removed google part from code
```
"adminUsers": {
    "xxxxxxxxxxxxxxxx": true
  },
...

**Comment by JimKay1941** [comment]
How do you know you have admin rights? Everything looks exactly the same to me as before and it appears that I cannot do anything. I cannot even create a new topic.

**Comment by bsde1234** [comment]
check my above comment https://github.com/hoppula/refire-forum/issues/29#issuecomment-563048742

**Comment by bsde1234** [comment]
You need to open a thread to see delete , edit permissions. But I dont know how to create new category in forum. settings says not implemented

**Comment by JimKay1941** [comment]
Yes, I just found all of that, but there isn't much of anything there.

In the beginning, I tried to do all this on Windows 10 but the javascripts are not in a format acceptable to Windows. After trying to fix a big bunch of them, I created an Ubuntu under Hyper-V and have been working it from there. I use one of my OneDrive accounts to transfer files from Windows to Ubuntu. (I have not figured out how to do a file-share.)

You did a really good job in removing the 'google:' piece. That certainly made a difference. But it also means the README.md file for installation is rather wrong. 

I'll leave this alive, but I doubt I'll use it for anything serious. I had hopes for it, but it's pretty bad, if you ask me.

I even installed Visual Studio Code and tried to poke around under Ubuntu hoping I'd figure out how the system works. That learning curve is very challenging. To me, VS Code is totally NOT-intuitive.

I get lost just reading about all the windows and menus.

Cheers,

**Comment by JimKay1941** [comment]
I've been happily using Visual Studio for about 15 years but I just don't get the hang of VS Code.

**Comment by bsde1234** [comment]
I think you can add different catefories by editing bootstrap.json file. Even though it is a tiny app we can do some basic job with it. So only for small business I think.

**Comment by JimKay1941** [comment]
Just that fact that you have to wipe out the entire database every time you make an update to the administrative privileges, that kind of rules this out as a useful forum system.

Imagine, a couple of years from now, and you decide to add one more administrator? POOF, all your users and posted messages are gone, gone, gone.

I think the best I can do is delete the whole thing and continue on with phpBB. 

The only good thing I can say for Hoppula is that it's configured for Firebase. That was a real accomplishment. But as a forum, it leaves too much to be desired.

**Comment by bsde1234** [comment]
Yes, that's a big problem. So I also think to look for another script based firebase. Lots of project in GitHub

**Comment by JimKay1941** [comment]
Yes, there are. But in the future, I'll stay away from any project that as been idled for a few years. 

The original authors have voted with their feet. 

Take a good look at phpBB which is not, as far as I know, on Github.

**Comment by bsde1234** [comment]
phpBB is much better, but requires more resources.

**Comment by JimKay1941** [comment]
With nobody logged on to phpBB, my workstation is:
cpu frequency 2801
cpu active 2%
Memory 34%
Swap 28%

Granted, I installed the whole thing on an SSD, which certainly helps performance. The machine is about seven years old. 

How many users do you expect to have on at one time?

**Comment by bsde1234** [comment]
Looks good as compared to other bb solutions. Here firebase is free or cheap on pay as you go. Mine is start up small business. Max 100 users at a time.

**Comment by bsde1234** [comment]
for database wipe issue, I think you can manually add categories or admin in database without adding to bootstrap.json file and don't run npm run bootstrap again.

**Comment by hoppula** [comment]
Whoa, it's not required to wipe out your database when you add admin users, just add one to `adminUsers` using Firebase console :) 
But you're correct in your assessment, I wouldn't recommend this forum in it's current state for anyone as there are no active maintainers. But it could serve as a good inspiration if you were to implement modern real-time forum using Firebase & React.

**Comment by bsde1234** [comment]
@hoppula Thanks for this project. Can you please show the boards and categories structure of the demo forum in db or bootstrap.json?

**Comment by hoppula** [comment]
Sure, here's categories: 
```
[ {
  "active" : true,
  "boards" : {
    "announcements" : true,
    "general" : true,
    "testing" : true
  },
  "title" : "General"
}, {
  "active" : true,
  "boards" : {
    "refire-app-issues" : true,
    "refire-forum-issues" : true,
    "refire-issues" : true
  },
  "title" : "Support"
}, {
  "active" : true,
  "boards" : {
    "refire-app-ideas" : true,
    "refire-forum-ideas" : true,
    "refire-ideas" : true
  },
  "title" : "Feature requests & ideas"
} ]
```

And here's part (Off-topic) of boards:
```
{
  "general" : {
    "active" : true,
    "threads" : {
      "-KCydR_YgaspWpvL_8gg" : true,
      "-KDdaYa4V-xVF1iHsHGV" : true,
      "-KE0XoRV6TeJRyZo0TlR" : true,
      "-KEmuaR3XN8ho2hD0x9o" : true,
      "-KF6_ohAnpgL6IqvQgSa" : true,
      "-KG_vy7pvTHedv3VLorj" : true,
      "-KcEYumTFxOX32ai_f-P" : true,
      "-KcRXiZF9QYwlzE4O4Ep" : true,
      "-Kf3aSD-j7cH4IkEqwvY" : true,
      "-KjwK6fP26K2eHN8ws2D" : true,
      "-KpW_BqrfCrnOnoUvEpk" : true,
      "-KrI-OYsdCADJI6wsAkq" : true,
      "-KsVP8xKNTV3fSAkarIv" : true,
      "-KsVPBuWfCfqvOfYdrTe" : true,
      "-KtkCioGwlJ2irf92XBb" : true,
      "-KuJooJn9bA-jkQuMumZ" : true,
      "-KuJor0ExKtQC76IPL64" : true,
      "-KuJp2VycSd4JDrGY5ag" : true,
      "-Kuu7bkQvuWw2lZigwor" : true,
      "-L-_E5tq-ZCRR2af_8Mh" : true,
      "-L-wkS2DvEW8ecgzVb7R" : true,
      "-L0jcAELg9qaWxiHxRDQ" : true,
      "-L2iAwmRfPQXS0eelRtU" : true,
      "-L3iZQfer6VEdAlOFbQN" : true,
      "-LAOKeROrL7fqj_ZgiFr" : true,
      "-LRjiN-QRrdyjIZySU5m" : true,
      "-L_wwCdfjl-t3Wj22_l0" : true,
      "-LaQu0XjjRzTNCMKTsaN" : true,
      "-Lat12i0XiYRC5LFF15F" : true,
      "-LbimQEuSWTNJb7GW003" : true,
      "-Lo3LsJwDJ9URrVoaf0s" : true,
      "-Lojl5N03C7GutB8R-tV" : true,
      "-LubZyiPlWKsy-0aaFpu" : true
    },
    "title" : "Off topic"
  }
}
```

**Comment by bsde1234** [comment]
Thanks for the input. Is it possible restrict access of a board, say announcement to only admin? may be in db rules?

**Comment by bsde1234** [comment]
Actually I already setup db, can you please check it @hoppula 
```
...
"boards" : [ {
    "active" : true,
    "threads" : [ true ],
    "title" : "Announcements"
  }, {
    "active" : true,
    "title" : "General disc"
  }, {
    "active" : true,
    "title" : "English Support Section"
  }, {
    "active" : true,
    "title" : "Malayalam Support Section"
  } ],
  "categories" : [ {
    "active" : true,
    "boards" : [ true ],
    "title" : "Announcements"
  }, {
    "active" : true,
    "boards" : [ null, true ],
    "title" : "Tutorials and Guides"
  }, {
    "active" : true,
    "boards" : {
      "2" : true
    },
    "title" : "English Support Section"
  }, {
    "active" : true,
    "boards" : {
      "3" : true
    },
    "title" : "Malayalam Support Section"
  } ],
  "posts" : [ {
    "body" : "refire-forum has been successfully setup",
    "createdAt" : "1457180850877",
    "threadId" : "0",
    "user" : {
      "displayName" : "Refire Bootstrap",
      "id" : "not-available",
      "image" : ""
    }
  } ],
  "settings" : {
    "BOARD_PAGE_SIZE" : 10,
    "DATE_FORMAT" : "DD.MM.YYYY",
    "THREAD_PAGE_LIMIT" : 5,
    "THREAD_PAGE_SIZE" : 10
  },
  "threads" : [ {
    "boardId" : "0",
    "createdAt" : "1457180850877",
    "lastPostAt" : "1457180850877",
    "posts" : [ true ],
    "title" : "Welcome",
    "user" : {
      "displayName" : "Refire Bootstrap",
      "id" : "not-available",
      "image" : ""
    }
  } ],
...
```

**Comment by hoppula** [comment]
Sorry, I do not have time to help you more at the moment, I hope you can figure it out :)

**Comment by bsde1234** [comment]
@hoppula When you get spare time, please tell me how to lock/restrict access( create thread ) to a board to only admin

**Comment by bsde1234** [comment]
Hi, any way to lock a forum not topic. Also any easy way to ban user? Thanks.
