### ISSUE TITLE
Why html is not working

### ISSUE THREAD

**Issue by bsde1234** [hoppula/refire-forum#31]
Why html is not rendering in the forum?

**Comment by simonho1989** [comment]
did you copy the index.html into dist/index.html?

**Comment by bsde1234** [comment]
@simonho1989 I mean markdown working except table, but html rendering not working in post body. It also not working demo forum here..May be the developer not enabled it.

**Comment by hoppula** [comment]
Yeah, posting HTML in post body is disallowed to prevent injecting malicious scripts.

**Comment by bsde1234** [comment]
Thanks @hoppula for conformation.
