### ISSUE TITLE
Where to set "Firesbase value" - Data:set is not a Firebase command

### ISSUE THREAD

**Issue by yarnball** [hoppula/refire-forum#6]
Hi,

Great work on this! I'm trying to set it up however the first part ("Change firebase value to your app name in firebase.json") is not clear.

Could you please tell me exactly what I need to update in firebase.json?

Also, maybe related to the above, but when I try running "npm run bootstrap", I get this error:

"data:set is not a Firebase command

data:set has been renamed, please run firebase database:set instead"

Thanks

**Comment by hoppula** [comment]
Hi and thanks! 

I recently changed the `firebase-tools` dependency to version 3, which uses Firebase Javascript API v3. 

However, in v3 some CLI commands have been deprecated and they would need to be changed to new ones. There's an open PR for these changes (#5) but it's still missing a separate command for deploying security rules (I guess the missing command is `firebase deploy --only database`).

So feel free to try out the changes in that PR, they might be enough to get you up and running. I'll try to get the npm scripts fixed soon.
